Repository RecipeMatch/backend, pull requests merged in 2025-04, with the labels that each got.

#123 [refactor/#122] 게시물 관련 DTO 유지보수
  src/main/java/org/example/recipe_match_backend/domain/post/dto/response/post/PostResponse.java
Labels: 리팩토링

#129 [refactor/#128] 레시피 난이도 선정 부분 전반적인 수정
  src/main/java/org/example/recipe_match_backend/domain/post/domain/PostComment.java
  src/main/java/org/example/recipe_match_backend/domain/recipe/service/RecipeService.java
Labels: 리팩토링

#131 [refactor/#130] 레시피 정보에 인분 추가
  src/main/java/org/example/recipe_match_backend/domain/ingredient/controller/IngredientController.java
  src/main/java/org/example/recipe_match_backend/domain/ingredient/service/IngredientService.java
  src/main/java/org/example/recipe_match_backend/domain/recipe/domain/Recipe.java
  src/main/java/org/example/recipe_match_backend/domain/recipe/dto/mapping/RecipeJsonDTO.java
  src/main/java/org/example/recipe_match_backend/domain/recipe/dto/request/recipe/RecipeRequest.java
  src/main/java/org/example/recipe_match_backend/domain/recipe/dto/response/recipe/RecipeResponse.java
  src/main/java/org/example/recipe_match_backend/domain/recipe/service/RecipeService.java
  src/main/java/org/example/recipe_match_backend/domain/tool/controller/ToolController.java
  src/main/java/org/example/recipe_match_backend/domain/tool/service/ToolService.java
  src/main/resources/recipe.json
Labels: 리팩토링

#133 [feat/#132] 네이버 검색 쇼핑 API를 이용하여 부족한 재료에 대한 상품 추천 기능 구현
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/controller/RecipeRecommendationController.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/dto/ItemDto.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/dto/ProductDto.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/dto/response/NaverShoppingResponse.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/dto/response/ProductRecommendationResponse.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/service/RecipeRecommendationService.java
  src/main/java/org/example/recipe_match_backend/global/config/NaverShoppingClient.java
  src/main/resources/application.yml
Labels: 기능 구현

#135 [feat/#134] 상품 검색 기능 (네이버 쇼핑 검색 API 사용)
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/controller/RecipeRecommendationController.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/dto/response/SearchProductRecommendationResponse.java
  src/main/java/org/example/recipe_match_backend/global/api/naverProducts/service/RecipeRecommendationService.java
Labels: 기능 구현

#137 [feat/#136] chatgpt api 통신 구현
  build.gradle.kts
  src/main/java/org/example/recipe_match_backend/RecipeMatchBackendApplication.java
Labels: 기능 구현

#150 [chore/#149] recipe 정보 수정
  src/main/resources/recipe.json
Labels: 환경설정
